PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX hedera: <https://bhash.dev/hedera/core/>

SELECT ?member ?memberName ?committee ?committeeName ?hip
WHERE {
  ?assignment a hedera:RoleAssignment ;
              hedera:assignsRole hedera:ValidatorOnboardingSteward ;
              hedera:hasParticipant ?committee , ?member ;
              hedera:supportedBy ?decision .

  ?committee a hedera:GovernanceBody ;
             dcterms:title ?committeeName .

  ?member a hedera:Actor ;
          dcterms:title ?memberName .
  FILTER NOT EXISTS { ?member a hedera:GovernanceBody }

  ?decision dcterms:identifier ?hip .
}
ORDER BY ?committeeName ?memberName
